### PR TITLE
Look up names->IDs in batches of 100

### PR DESCRIPTION
**Pull request by hugovk**
I put the list of the accounts I follow, about 400, into production.yaml but got a 403 Forbidden error.

This is because the call to `twitter.lookupUser` uses Twitter's `users/lookup`, which is limited to 100 users per request: https://dev.twitter.com/rest/reference/get/users/lookup

So, split the list into batches of 100 and look up 100 at a time.

---

When starting up, you get `HTTP Error 429: Too Many Requests` for some users, but that's to be expected making so many requests at once, but it still otherwise works.

```
$NODE_ENV=production node app.js
===================================================
Twelescreen starting, using Node v4.2.1
   info  - socket.io started
Streamer (1/3 start):  Fetching Twitter user IDs
Express server listening on port 3000
Streamer (1/3 finish): Fetching Twitter user IDs
Streamer (2/3 start):  Caching existing Tweets
Streamer (1/3 finish): Fetching Twitter user IDs
Streamer (3/3 start):      Listening for new Tweets
Streamer (3/3 continuing): Listening for new Tweets
===================================================
Streamer (1/3 finish): Fetching Twitter user IDs
default,
Streamer (1/3 finish): Fetching Twitter user IDs
Streamer (1/3 finish): Fetching Twitter user IDs
Streamer: Error fetching tweets for user id '149112537': Error: HTTP Error 429: Too Many Requests
Streamer: Error fetching tweets for user id '14798487': Error: HTTP Error 429: Too Many Requests
Streamer: Error fetching tweets for user id '3313059329': Error: HTTP Error 429: Too Many Requests
Streamer: Error fetching tweets for user id '2860590142': Error: HTTP Error 429: Too Many Requests
Streamer: Error fetching tweets for user id '3025174660': Error: HTTP Error 429: Too Many Requests
Streamer: Error fetching tweets for user id '3033968632': Error: HTTP Error 429: Too Many Requests
Streamer: Error fetching tweets for user id '3291286474': Error: HTTP Error 429: Too Many Requests
Streamer: Error fetching tweets for user id '208438555': Error: HTTP Error 429: Too Many Requests
Streamer: Error fetching tweets for user id '39482318': Error: HTTP Error 429: Too Many Requests
Streamer: Error fetching tweets for user id '3052317647': Error: HTTP Error 429: Too Many Requests
Streamer: Error fetching tweets for user id '3065691399': Error: HTTP Error 429: Too Many Requests
Streamer: Error fetching tweets for user id '2870426806': Error: HTTP Error 429: Too Many Requests
Streamer: Error fetching tweets for user id '2215404282': Error: HTTP Error 429: Too Many Requests
Streamer: Error fetching tweets for user id '1530155533': Error: HTTP Error 429: Too Many Requests
Streamer: Error fetching tweets for user id '3021367763': Error: HTTP Error 429: Too Many Requests
Streamer: Error fetching tweets for user id '145749531': Error: HTTP Error 429: Too Many Requests
Streamer: Error fetching tweets for user id '12341222': Error: HTTP Error 429: Too Many Requests
Streamer: Error fetching tweets for user id '1399609189': Error: HTTP Error 429: Too Many Requests
Streamer: Error fetching tweets for user id '588426987': Error: HTTP Error 429: Too Many Requests
Streamer: Error fetching tweets for user id '2918426355': Error: HTTP Error 429: Too Many Requests
default,

default,
default,
default,
   debug - client authorized
   info  - handshake authorized JzTEYj8FrrB3HBhrXR1g
   debug - setting request GET /socket.io/1/websocket/JzTEYj8FrrB3HBhrXR1g
   debug - set heartbeat interval for client JzTEYj8FrrB3HBhrXR1g
   debug - client authorized for 
   debug - websocket writing 1::
Connected client: JzTEYj8FrrB3HBhrXR1g
```

---

I also added .editorconfig so my editor knows to do two-space indents for this repo.
http://editorconfig.org/

### CODE REVIEW

**Comment by hugovk** [comment]
Hmm, but something else is needed, it's seems to be looping only about 8-9 of those ~400.

**Comment by philgyford** [comment]
Hmm, not sure I'll have time to take a look for a few weeks, so I can't really help right now, sorry. I wasn't anticipating anyone using so many accounts :)

**Comment by hugovk** [comment]
Ahem... https://github.com/philgyford/twelescreen/issues/2 :)

Yeah, no rush whatsoever!

**Comment by hugovk** [comment]
I think we can close this now :)

**Pull request closed without merging**
